# Generated by Django 3.0.8 on 2020-07-16 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0057_auto_20200709_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 14, 45, 25, 568349)),
        ),
    ]
