# Generated by Django 3.0.8 on 2020-07-16 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_auto_20200716_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 21, 6, 4, 850228)),
        ),
    ]
