# Generated by Django 3.0.8 on 2020-07-20 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_auto_20200716_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 28, 16, 695705)),
        ),
    ]
